#!/usr/bin/env bash

set -eou pipefail

name="${1:-}"

if [[ -z "$name" ]]; then
    echo "Usage: bfcpl <file.bf> [-o file] [-flags]"
    exit 1
fi
shift

output=""
rec_opt=false
rec_abe=false
rec_cmplr=false
save_asm=false
run_exec=false

verbose=false

in_type=0   # 0 = bf;   1 = bfvm
out_type=-1 # 0 = bfvm; 1 = bfasm;  2 = exec

opt_lvl=0   # clang++'s optimization level

cmplr_flags=()  # apparently bash has arrays


if [[ "$name" == *.bfvm ]]; then
    in_type=1
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -o)
            shift
            if [[ -z "$1" ]]; then
                echo "No file name after -o"
                exit 1
            fi
            output="$1"
            ;;
        -r-opt)
            rec_opt=true
            ;;
        -r-abe)
            rec_abe=true
            ;;
        -r-cmplr)
            rec_cmplr=true
            ;;
        -sasm)
            save_asm=true
            ;;
        -run)
            run_exec=true
            ;;
        -v|-verbose)
            verbose=true
            ;;
        -in=*)
            str="${1:4}"
            case "$str" in
                bf|brainfuck)
                    in_type=0 ;;
                bfvm)
                    in_type=1 ;;
                *)
                    echo "Invalid -in value: $str"
                    exit 1 ;;
            esac
            ;;
        -out=*)
            str="${1:5}"
            case "$str" in
                bfvm)
                    out_type=0 ;;
                asm|bfasm)
                    out_type=1 ;;
                exe|exec)
                    out_type=2 ;;
                *)
                    echo "Invalid -out value: $str"
                    exit 1 ;;
            esac
            ;;
        -O*)
            str="${1:2}"
            case "$str" in
                0|1|2|3)
                    opt_lvl="$str" ;;
                *)
                    echo "Invalid Optimization Level: $str"
                    exit 1 ;;
            esac
            ;;
        --*)
            str="${1:1}"
            cmplr_flags+=("$str")
            ;;
        *)
            echo "Invalid argument: $1"
            exit 1
            ;;
    esac
    shift
done


if [[ "$out_type" -eq -1 ]]; then
    case "$output" in
        *bfvm)
            out_type=0 ;;
        *.bfasm)
            out_type=1 ;;
        *)
            out_type=2 ;;
    esac
    [[ "$verbose" == true ]] && echo "No output type given, inferring $out_type"
fi
if [[ -z "$output" ]]; then
    output="${name%.*}"
    case "$out_type" in
        0)
            output="$output.bfvm"
            ;;
        1)
            output="$output.bfasm"
            ;;
        2)
            # output="$output"
            ;;
    esac
    [[ "$verbose" == true ]] && echo "No output file given, outputting to $output"
fi


build_obj() {   # this primitive language has functions too
    local src="$1"
    local obj="$2"
    local force="$3"

    if [[ "$force" == true || ! -f "$obj" || "$src" -nt "$obj" ]]; then
        [[ "$verbose" == true ]] && echo "Recompiling file $src to $obj"
        clang++ -c "$src" -o "$obj" "-O$opt_lvl"
        return 0
    fi
    return 1
}

if [[ src/bf.hpp -nt build/bf_optimize.o || src/bf.hpp -nt build/bf_asm_be.o
    || src/bf.hpp -nt build/bf_cmplr.o ]]; then
    rec_opt=true
    rec_abe=true
    rec_cmplr=true
fi
if [[ src/bf_asm_be_asm_man.cpp -nt build/bf_asm_be.o ]]; then
    rec_abe=true
fi


if [[ ! -d build ]]; then
    [[ "$verbose" == true ]] && echo "build/ does not exist, creating it"
    mkdir -p build
fi

rec_everything=false
build_obj src/bf_optimize.cpp   build/bf_optimize.o "$rec_opt"      &&  rec_everything=true
build_obj src/bf_asm_be.cpp     build/bf_asm_be.o   "$rec_abe"      &&  rec_everything=true
build_obj src/bf_cmplr.cpp      build/bf_cmplr.o    "$rec_cmplr"    &&  rec_everything=true


out_asm="$output.s"

if [[ "$save_asm" == false ]]; then
    out_asm=$(mktemp "/tmp/bf_asm_XXXXXX.s")
    [[ "$verbose" == true ]] && echo "Storing temporary assembly file in $out_asm"
fi


if [[ "$rec_everything" == true || ! -f bf_cmplr ]]; then
    [[ "$verbose" == true ]] && echo "Recompiling bf_cmplr"
    clang++ build/bf_cmplr.o build/bf_asm_be.o build/bf_optimize.o -o bf_cmplr "-O$opt_lvl"
fi

[[ "$verbose" == true ]] && echo "Compiling $name to $output"
if [[ "$out_type" -eq 2 ]]; then
    ./bf_cmplr "$name" -o "$out_asm" "-in=$in_type" "-out=2" "${cmplr_flags[@]}"
    clang++ src/bf_asm.cpp "$out_asm" -o "$output"
    if [[ "$save_asm" == false ]]; then
        rm -f "$out_asm"
    fi
    if [[ "$run_exec" == true ]]; then
        [[ "$verbose" == true ]] && echo "Running ./$output
---------------------------------------"
        "./$output"
    fi
else
    ./bf_cmplr "$name" -o "$output" "-in=$in_type" "-out=$out_type" "${cmplr_flags[@]}"
fi
